export const ITEMS_PER_PAGE = 20;

export const LEAGUE_TEAMS: Record<string, string[]> = {
  "Premier League": [
    "Chelsea",
    "Tottenham",
    "Arsenal",
    "Manchester United",
    "Manchester City",
    "Liverpool",
    "Newcastle",
    "Brighton",
    "West Ham",
    "Aston Villa",
    "Crystal Palace",
    "Fulham",
    "Brentford",
    "Wolves",
    "Everton",
    "Nottingham Forest",
    "Burnley",
    "Sheffield United",
    "Luton",
    "Bournemouth",
  ],
  "La Liga": [
    "Real Madrid",
    "Barcelona",
    "Atletico Madrid",
    "Sevilla",
    "Real Sociedad",
    "Villarreal",
    "Real Betis",
    "Valencia",
    "Athletic Bilbao",
    "Getafe",
    "Osasuna",
    "Rayo Vallecano",
    "Celta Vigo",
    "Mallorca",
    "Las Palmas",
    "Alaves",
    "Cadiz",
    "Granada",
    "Almeria",
  ],
  "Serie A": [
    "Juventus",
    "AC Milan",
    "Inter Milan",
    "Napoli",
    "Atalanta",
    "Roma",
    "Lazio",
    "Fiorentina",
    "Bologna",
    "Torino",
    "Monza",
    "Genoa",
    "Lecce",
    "Frosinone",
    "Udinese",
    "Sassuolo",
    "Cagliari",
    "Verona",
    "Empoli",
    "Salernitana",
  ],
  Bundesliga: [
    "Bayern Munich",
    "Borussia Dortmund",
    "RB Leipzig",
    "Bayer Leverkusen",
    "Eintracht Frankfurt",
    "Freiburg",
    "Hoffenheim",
    "Wolfsburg",
    "Augsburg",
    "Werder Bremen",
    "Bochum",
    "Union Berlin",
    "Mainz",
    "Cologne",
    "Darmstadt",
    "Heidenheim",
    "Gladbach",
    "Stuttgart",
  ],
  "Ligue 1": [
    "PSG",
    "Marseille",
    "Monaco",
    "Lyon",
    "Lille",
    "Nice",
    "Lens",
    "Rennes",
    "Reims",
    "Toulouse",
    "Montpellier",
    "Strasbourg",
    "Nantes",
    "Brest",
    "Le Havre",
    "Metz",
    "Lorient",
    "Clermont",
  ],
};

export const VIRTUAL_LIST_SPACING = 16;
export const VIRTUAL_LIST_DEFAULT_ITEM_HEIGHT = 200;
export const INFINITE_SCROLL_THRESHOLD = 200;

