export const ITEMS_PER_PAGE = 20;

export const LEAGUE_TEAMS: Record<string, string[]> = {
  "Premier League": [
    "Chelsea",
    "Tottenham",
    "Arsenal",
    "Manchester United",
    "Manchester City",
    "Liverpool",
    "Newcastle",
    "Brighton",
    "West Ham",
    "Aston Villa",
    "Crystal Palace",
    "Fulham",
    "Brentford",
    "Wolves",
    "Everton",
    "Nottingham Forest",
    "Burnley",
    "Sheffield United",
    "Luton",
    "Bournemouth",
  ],
  "La Liga": [
    "Real Madrid",
    "Barcelona",
    "Atletico Madrid",
    "Sevilla",
    "Real Sociedad",
    "Villarreal",
    "Real Betis",
    "Valencia",
    "Athletic Bilbao",
    "Getafe",
    "Osasuna",
    "Rayo Vallecano",
    "Celta Vigo",
    "Mallorca",
    "Las Palmas",
    "Alaves",
    "Cadiz",
    "Granada",
    "Almeria",
  ],
  "Serie A": [
    "Juventus",
    "AC Milan",
    "Inter Milan",
    "Napoli",
    "Atalanta",
    "Roma",
    "Lazio",
    "Fiorentina",
    "Bologna",
    "Torino",
    "Monza",
    "Genoa",
    "Lecce",
    "Frosinone",
    "Udinese",
    "Sassuolo",
    "Cagliari",
    "Verona",
    "Empoli",
    "Salernitana",
  ],
  Bundesliga: [
    "Bayern Munich",
    "Borussia Dortmund",
    "RB Leipzig",
    "Bayer Leverkusen",
    "Eintracht Frankfurt",
    "Freiburg",
    "Hoffenheim",
    "Wolfsburg",
    "Augsburg",
    "Werder Bremen",
    "Bochum",
    "Union Berlin",
    "Mainz",
    "Cologne",
    "Darmstadt",
    "Heidenheim",
    "Gladbach",
    "Stuttgart",
  ],
  "Ligue 1": [
    "PSG",
    "Marseille",
    "Monaco",
    "Lyon",
    "Lille",
    "Nice",
    "Lens",
    "Rennes",
    "Reims",
    "Toulouse",
    "Montpellier",
    "Strasbourg",
    "Nantes",
    "Brest",
    "Le Havre",
    "Metz",
    "Lorient",
    "Clermont",
  ],
};

export const VIRTUAL_LIST_SPACING = 16;
export const VIRTUAL_LIST_DEFAULT_ITEM_HEIGHT = 200;
export const INFINITE_SCROLL_THRESHOLD = 200;

/**
 * 기자 공신력 분류
 * 0티어, 1티어, 1.5티어 → 공신력 1 (🌕)
 * 2티어 → 공신력 2 (🌓)
 * 3티어 → 공신력 3 (🌒)
 */

// 공신력 1 (0티어, 1티어, 1.5티어)
export const CREDIBILITY_TIER_1_JOURNALISTS = [
  // 0티어
  "tombogert",
  "CLMerlo",
  "MikeVerweij",
  "SaberDesfa",
  "Tanziloic",
  "mohamedbouhafsi",
  "romeoagresti",
  "RNBVB",
  "MelchorRuizCope",
  "MarioTorrejon",
  "JLSanchez78",
  "AranchaMOBILE",
  "Belen_Boli",
  "rubenuria",
  "HectorGomezG",
  "howardnurse",
  "sistoney67",
  "SimonPeach",
  "David_Onstein",
  // 1티어
  "lauriewhitwell",
  "Jack_Gaughan",
  "JamesPearceLFC",
  "_pauljoyce",
  "charles_watts",
  "AlasdairGold",
  "SkySportsLyall",
  "pokeefe1",
  "greggevans40",
  "JPercyTelegraph",
  "LiamKeen_Star",
  "stevemadeley78",
  "TimSpiers",
  "RobTannerLCFC",
  "PhilHay_",
  "AndyNaylorBHAFC",
  "JTansey90",
  "Paddy_Boyland",
  "ElBobble",
  "peterrutzler",
  "DTathletic",
  "nottmtails",
  "Plettigoal",
  "berger_pj",
  "honigstein",
  "philipphinze24",
  "MatteMoretto",
  "SidLowe",
  "AntoVitiello",
  "86_longo",
  "MatteoBarzaghi",
  "FabriceHawkins",
  "RikElfrink",
  "MarcoTimmer",
  "ShamoonHafez",
  // 1.5티어
  "FabrizioRomano",
  "fraporzio95",
  "DiMarzio",
  "Guillaumemp",
  "JamesHorncastle",
  "hirsty_times",
  "TelegraphDucker",
  "mjcritchley",
  "Matt_Law_DT",
  "sjstandardsport",
  "liamtwomey",
  "_ChrisBascombe",
  "neiljonesecho",
  "_paulgorst",
  "DaveOCKOP",
  "dmlynch",
  "DominicKing_DM",
  "Simon_Hughes__",
  "ChrisWheatley_",
  "MarkMBryans",
  "henrywinter",
  "amylawrence71",
  "johncrossmirror",
  "BenDinnery",
  "JacobSteinberg",
  "Dan_KP",
  "CharlieEccleshar",
  "JBlackwell22",
  "RobDorsettSky",
  "DanSheldon",
  "LukeEdwardsTele",
  "ChrisDHWaugh",
  "CraigHope_DM",
  "JacobWhitehead",
  "DanRoan",
  "AdamCrafton",
  "NathanGissing",
  "MarioCortegana",
  "EduPidal",
  "albert_roge",
  "josepcapdevila",
  "moillorens",
  "RogerTorello",
  "gerardromero",
  "tjuanmarti",
  "ManuelBonke",
] as const;

// 공신력 2 (2티어)
export const CREDIBILITY_TIER_2_JOURNALISTS = [
  "ConstantinEckner",
  "FredrikANFiltvedt",
  "LaurensJulien",
  "JamieJackson___",
  "cfbayern",
  "DeanJonesBR",
  "JamesOlley",
  "AndyMitten",
  "alex_crook",
  "samuelluckhurst",
  "AlexCTurk",
  "SamLee",
  "SimonMullock",
  "benjacobs",
  "NizaarKinsella",
  "SiPhillipsSport",
  "PaulOKeeffe",
  "TomCollomosse",
  "dominicfifield",
  "NickPurewal",
  "ChrisWheelerDM",
  "MattLawton",
  "TomRoddy",
  "RobHarris",
  "SamJDean",
  "JasonBurt",
  "DermotCorrigan",
  "MikeMcGrath",
  "DharmeshSheth",
  "jonathanliew",
  "SammyMokbel_DM",
  "AngeloMangiante",
  "PasqualeGuarro",
  "jfelixdiaz",
  "luis_rojo",
  "siqueRodriguez",
  "HelenaCondis",
  "victor_nahe",
  "ferran_martinez",
  "ferran_martineyo",
  "kikemarin",
  "LoicTanzi",
  "KavehSolhekol",
  "JeremyWilson",
  "GiovanniAlbanese",
  "JamesBenge",
  "Simon_Collins",
  "Manu_Sainz",
  "TobiasAltschaffl",
  "MarcSchmidt",
  "SachaTavolieri",
  "MikeKeegan",
  "ChristianOrloff",
  "Santi_Aouna",
  "JamesSharpe92",
] as const;

// 공신력 3 (3티어)
export const CREDIBILITY_TIER_3_JOURNALISTS = [
  "IndyKaila",
  "GuillemBalague",
  "sampilger",
  "DuncanCastles",
  "jamesrobsonMEN",
  "RobDawsonESPN",
  "JasonBurt",
  "NicoSchira",
  "JanAageFjortoft",
  "DavidAmoyal",
  "DavidMurdoch",
  "DuncanWright",
  "MattHughesDM",
  "IanLadyman_DM",
  "JimWhite",
  "TyMarshall",
  "AlexisBernard10",
  "GianluigiLongari",
  "AlfredoPedulla",
  "migueldelaney",
  "AdrianKajumba",
  "JoseAlvarezH",
  "DiegoTorres",
] as const;

